### ISSUE TITLE
Multiplayer Issue in Unity-CrypticCabinet: Stuck After Hosting with Join Code

### ISSUE THREAD

**Issue by B14ckFox** [oculus-samples/Unity-CrypticCabinet#1]
## Environment
- **Unity version:** [2022.3.16f1]
- **Deployment platform:** [Android]

## Issue Description
I am encountering an issue with the Unity-CrypticCabinet project during multiplayer deployment. The game becomes unresponsive after initiating a host session and then confirming the join code.

## Steps to Reproduce
1. Launch the game.
2. Select 'Multiplayer' and then 'Host'.
3. A join code is displayed, and I click the 'OK' button.
4. The game does not proceed to the next step and remains stuck on this screen.

## Expected Behavior
After clicking 'OK' with the join code, the game should proceed to the next stage, allowing other players to join or continuing the hosting process.

## Additional Context
- The issue does not occur when using a link cable.
- Photon is configured correctly as per documentation.

I would appreciate any insights or suggestions on how to resolve this issue, particularly if there are any specific considerations for multiplayer deployment that I might have missed.

**Comment by AlexThiv** [comment]
Hi @BlackFox16,
Thanks for raising the issue. Would you be able to provide the logs when you press on the confirm button on the message showing the Room code. `adb logcat -s Unity`

**Comment by B14ckFox** [comment]
Fusion.Photon.Realtime.LoadBalancingClient:OnStatusChanged(StatusCode)
01-11 17:55:52.311  W Unity   : ExitGames.Client.Photon.EnetPeer:DispatchIncomingCommands()
01-11 17:55:52.311  W Unity   : ExitGames.Client.Photon.PhotonPeer:DispatchIncomingCommands()
01-11 17:55:52.311  W Unity   : ExitGames.Client.Photon.PhotonPeer:Service()
01-11 17:55:52.311  W Unity   : Fusion.Photon.Realtime.FusionRelayClient:Update()
01-11 17:55:52.311  W Unity   : Fusion.CloudCommunicator:Service()
01-11 17:55:52.311  W Unity   : Fusion.CloudServices:Update()
01-11 17:55:52.311  W Unity   : Fusion.NetworkRunner:Update()
01-11 17:55:52.311  W Unity   :
01-11 17:55:52.312  E Unity   : InvalidOperationException: Behaviour not initialized: Object not set.
01-11 17:55:52.312  E Unity   :   at Fusion.NetworkBehaviourUtils.ThrowIfBehaviourNotInitialized (Fusion.NetworkBehaviour behaviour) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.312  E Unity   :   at CrypticCabinet.Passthrough.PassthroughConfigurator.RPC_SetLut (CrypticCabinet.Passthrough.ELutId lutID, System.Single blend, Fusion.RpcInfo info) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.312  E Unity   :   at Fusion.NetworkRunner.Shutdown (System.Boolean destroyGameObject, Fusion.ShutdownReason shutdownReason, System.Boolean forceShutdownProcedure) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.312  E Unity   :   at Fusion.Photon.Realtime.ConnectionCallbacksContainer.OnDisconnected (Fusion.Photon.Realtime.DisconnectCause cause) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.312  E Unity   :   at Fusion.Photon.Realtime.LoadBalancingClient.OnStatusChanged (ExitGames.Client.Photon.StatusCode statusCode) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.312  E Unity   :   at ExitGames.Client.Photon.EnetPeer.DispatchIncomingCommands () [0
01-11 17:55:52.315  E Unity   : InvalidOperationException: Behaviour not initialized: Object not set.
01-11 17:55:52.315  E Unity   :   at Fusion.NetworkBehaviourUtils.ThrowIfBehaviourNotInitialized (Fusion.NetworkBehaviour behaviour) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.315  E Unity   :   at CrypticCabinet.Passthrough.PassthroughConfigurator.RPC_SetLut (CrypticCabinet.Passthrough.ELutId lutID, System.Single blend, Fusion.RpcInfo info) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.315  E Unity   :   at Fusion.NetworkRunner.Shutdown (System.Boolean destroyGameObject, Fusion.ShutdownReason shutdownReason, System.Boolean forceShutdownProcedure) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.315  E Unity   :   at Fusion.Photon.Realtime.ConnectionCallbacksContainer.OnDisconnected (Fusion.Photon.Realtime.DisconnectCause cause) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.315  E Unity   :   at Fusion.Photon.Realtime.LoadBalancingClient.OnStatusChanged (ExitGames.Client.Photon.StatusCode statusCode) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.315  E Unity   :   at ExitGames.Client.Photon.EnetPeer.DispatchIncomingCommands () [0
01-11 17:55:52.339  E Unity   : ColocationLauncher: We did not save the local anchor to the cloud
01-11 17:55:52.339  E Unity   : ColocationPackage.<CreateAlignmentAnchor>d__37:MoveNext()
01-11 17:55:52.339  E Unity   : Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(TResult)
01-11 17:55:52.339  E Unity   : ColocationPackage.<SaveLocalAnchorsToCloud>d__10:MoveNext()
01-11 17:55:52.339  E Unity   : Cysharp.Threading.Tasks.UniTaskCompletionSource`1:TrySignalCompletion(UniTaskStatus)
01-11 17:55:52.339  E Unity   : OVRSpatialAnchor:InvokeMultiAnchorDelegate(UInt64, OperationResult, MultiAnchorActionType)
01-11 17:55:52.339  E Unity   : OVRManager:UpdateHMDEvents()
01-11 17:55:52.339  E Unity   : OVRManager:Update()
01-11 17:55:52.339  E Unity   :
01-11 17:55:52.348  E Unity   : InvalidOperationException: Error when accessing PhotonNetworkData.ColocationGroupCount. Networked properties can only be accessed when Spawned() has been called.
01-11 17:55:52.348  E Unity   :   at CrypticCabinet.Photon.Colocation.PhotonNetworkData.get_ColocationGroupCount () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at CrypticCabinet.Photon.Colocation.PhotonNetworkData.GetColocationGroupCount () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at ColocationPackage.ColocationLauncher.CreateNewColocatedSpace () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult (TResult result) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at ColocationPackage.ColocationLauncher.CreateAlignmentAnchor () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult (TResult result) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.348  E Unity   :   at ColocationPackage.SharedAnchorManager.SaveLocalAnch
01-11 17:55:52.350  E Unity   : OperationCanceledException: The operation was canceled.
01-11 17:55:52.350  E Unity   :   at Cysharp.Threading.Tasks.AsyncUnityEventHandler`1[T]..cctor () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  E Unity   :   at Cysharp.Threading.Tasks.UniTask+WaitUntilPromise.GetResult (System.Int16 token) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  E Unity   :   at CrypticCabinet.Player.CrypticCabinetPlayer.Spawned () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  E Unity   :   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  E Unity   :   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  E Unity   :   at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetCanceled (System.Threading.CancellationToken cancellationToken) [0x00000] in <00000000000000000000000000000000>:0
01-11 17:55:52.350  6160  6182 E Unity   :   at Cysharp.Threading.Tasks.U

**Comment by AlexThiv** [comment]
@BlackFox16 Thanks for the logs, I would need the logs that happened before this. It seems like the status changed to disconnected and that would be why you are not moving through. But getting the logs before would help me understand why you got disconnected. Thanks

**Comment by AlexThiv** [comment]
Please respond with more information if you are still running into this issue.
