### ISSUE TITLE
Can we Modify and post Pull request?

### ISSUE THREAD

**Issue by Demiseman** [oculus-samples/Unity-CrypticCabinet#4]
I fork the project to start testing at work with all the setup, if we find ways to upgrade It, can we put Push to Main later? (We fork)

**Comment by jasonmeisel** [comment]
We're happy to accept pull requests, particularly if they fix known issues! Check out [CONTRIBUTING.md](https://github.com/oculus-samples/Unity-CrypticCabinet/blob/main/CONTRIBUTING.md) for more info.
