### ISSUE TITLE
Instructions to clone repo link is incorrect

### ISSUE THREAD

**Issue by jimbaug** [oculus-samples/Unity-CrypticCabinet#5]
The instructions README step says to clone the repo (not the CODE section) do this:
git clone https://github.com/oculus-samples/Unity-Cryptic-Cabinet.git

But it should be this: (without Hyphen)
git clone https://github.com/oculus-samples/Unity-CrypticCabinet.git

**Comment by jasonmeisel** [comment]
Thanks for the report! This has been fixed in b6dc4efc95a65d76049b8f8fb5a339c64116f2d3 :)
