### ISSUE TITLE
Namespace or assempbly errors

### ISSUE THREAD

**Issue by PaoloSalvatico** [oculus-samples/Unity-CrypticCabinet#6]
Hi, after i opened the project on Unity version 2022.3.20, i couldn't do anything cause i received many errors about missing components or namespaces. I'll add a photo for more details, thanks

![Screenshot 2024-02-26 105323](https://github.com/oculus-samples/Unity-CrypticCabinet/assets/90765429/85d71adc-b649-4d01-9005-0267d420e7ab)

![Screenshot 2024-02-26 105236](https://github.com/oculus-samples/Unity-CrypticCabinet/assets/90765429/2bdebf55-573b-4c31-864f-c39ed3cc4ca1)

**Comment by AlexThiv** [comment]
Hi @PaoloSalvatico,

How did you get the project? It seems like you didn't get the lfs files.

Make sure to install lfs before cloning the project. If you only downloaded the zip, it won't have the right lfs files but rather there addresses to the lfs storage.

See the getting the code setion https://github.com/oculus-samples/Unity-CrypticCabinet?tab=readme-ov-file#getting-the-code

**Comment by PaoloSalvatico** [comment]
Hi Alex, thank you for the help, that was exactly the problem.
