### ISSUE TITLE
After upraded to v64 for Quest 3, Game cannot start

### ISSUE THREAD

**Issue by mayafishing** [oculus-samples/Unity-CrypticCabinet#7]
Just upgraded to v64 for the Quest 3 headset. Game failed to continue at the Analyzing room stage. Throwed the following error:

[OVRScenePlaneMeshFilter] Plane boundary triangulation failed.
UnityEngine.Debug:LogError (object)
OVRScenePlaneMeshFilter/TriangulateBoundaryJob:Execute () (at ./Library/PackageCache/com.meta.xr.sdk.core@64.0.0/Scripts/OVRScenePlaneMeshFilter.cs:256)
Unity.Jobs.IJobExtensions/JobStruct`1<OVRScenePlaneMeshFilter/TriangulateBoundaryJob>:Execute (OVRScenePlaneMeshFilter/TriangulateBoundaryJob&,intptr,intptr,Unity.Jobs.LowLevel.Unsafe.JobRanges&,int)

Tried to upgrade Meta SDK to v64, same error.

**Comment by AlexThiv** [comment]
@mayafishing thanks for raising this issue. Have you tried with the latest v65 SDK?
