### ISSUE TITLE
Multiplayer Game test

### ISSUE THREAD

**Issue by PaoloSalvatico** [oculus-samples/Unity-CrypticCabinet#8]
Hello, we are trying to play criptic cabinet online in local with 3 different quest 3 devices and we did it, but every time only 2 out of 3 devices successfully colocate in the right spot and the third device is located wrong. The main issue is that the working devices are not always the same, sometimes device 1 and device 2 work adn sometimes 1 and 3, this doesn't make any sense, do you have any advice?

Metagate

**Comment by jasonmeisel** [comment]
Hi @PaoloSalvatico, could you provide us with device logs from the device that fails to colocate? Use the following command before playing: `adb logcat -s "Unity"`
